function plan = buildfile
%BUILDFILE Reproducible MATLAB validation entry points for local and CI use.

plan = buildplan(localfunctions);

plan("test-unit") = matlab.buildtool.tasks.TestTask( ...
    "matlab/tests/TestControlBench.m", ...
    SourceFiles="matlab/controlbench", ...
    TestResults=["artifacts/matlab-unit/junit.xml", ...
        "artifacts/matlab-unit/report.html"]);

plan("test-integration") = matlab.buildtool.tasks.TestTask( ...
    "matlab/tests/TestControlBenchIntegration.m", ...
    SourceFiles=["matlab/controlbench","ADMM_Solver.m","Agent.m", ...
        "Agent_data.m","Neighbor.m","Neighbor_data.m","Solution.m"], ...
    TestResults=["artifacts/matlab-integration/junit.xml", ...
        "artifacts/matlab-integration/report.html"]);

plan("ci") = matlab.buildtool.Task( ...
    Description="Run unit and solver-backed ControlBench tests", ...
    Dependencies=["test-unit","test-integration"]);

plan.DefaultTasks = "ci";
end
